AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Actions-Test-001

  Sample SAM Template for testing GitHub Actions cache and parallel build

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  HelloWorldFunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Function1
      Handler: helloworld.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64

  HelloWorldFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Function2
      Handler: helloworld.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64

  HelloWorldFunction3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Function3
      Handler: helloworld.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64

  HelloWorldFunction4:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Function4
      Handler: helloworld.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64

  HelloWorldFunction5:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Function5
      Handler: helloworld.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64

Outputs:
  HelloWorldFunction1:
    Description: "Hello World Lambda Function 1 ARN"
    Value: !GetAtt HelloWorldFunction1.Arn
